const fs = require('fs');

let code = fs.readFileSync('jewelry-data.js', 'utf8');

const newTryOnNecklaces = `
  {
    id: 'n_tryon_157',
    name: 'Exquisite Diamond Drop',
    category: 'necklace',
    type: 'necklace',
    glbFile: 'necklace15.glb',
    image: 'static/images/necklace/necklace157.png',
    color: '#c0c0c0',
    gemColor: '#e8f4ff',
    metalness: 0.95,
    roughness: 0.05,
    price: 'Rs. 240,000',
    rating: 4.8,
    ratingCount: 12,
    material: 'Platinum + Diamonds',
    description: 'Beautiful Try-On necklace featuring a diamond drop.',
    tags: ['diamond', 'platinum', 'tryon'],
  },
  {
    id: 'n_tryon_159',
    name: 'Sapphire Elegance',
    category: 'necklace',
    type: 'necklace',
    glbFile: 'necklace45.glb',
    image: 'static/images/necklace/necklace159.png',
    color: '#d4a847',
    gemColor: '#1155cc',
    metalness: 0.92,
    roughness: 0.08,
    price: 'Rs. 210,000',
    rating: 4.9,
    ratingCount: 20,
    material: '22K Gold + Sapphires',
    description: 'Elegant sapphire try-on necklace.',
    tags: ['sapphire', 'gold', 'tryon'],
  },
  {
    id: 'n_tryon_162',
    name: 'Ruby Classic Collar',
    category: 'necklace',
    type: 'necklace',
    glbFile: 'necklace12.glb',
    image: 'static/images/necklace/necklace162.png',
    color: '#d4a847',
    gemColor: '#cc2233',
    metalness: 0.95,
    roughness: 0.06,
    price: 'Rs. 320,000',
    rating: 5.0,
    ratingCount: 8,
    material: '22K Gold + Rubies',
    description: 'Classic ruby collar necklace for Try-On.',
    tags: ['ruby', 'gold', 'collar'],
  },
  {
    id: 'n_tryon_163',
    name: 'Golden Grace',
    category: 'necklace',
    type: 'necklace',
    glbFile: 'necklace14.glb',
    image: 'static/images/necklace/necklace163.png',
    color: '#d4a847',
    gemColor: null,
    metalness: 0.94,
    roughness: 0.1,
    price: 'Rs. 180,000',
    rating: 4.7,
    ratingCount: 30,
    material: '22K Gold',
    description: 'Graceful solid gold try-on necklace.',
    tags: ['grace', 'gold', 'tryon'],
  },
`;

const newCatalogNecklaces = `
  {
    id: 'n_cat156',
    name: 'Royal Heritage Set',
    category: 'necklace',
    type: 'necklace',
    glbFile: 'necklace15.glb',
    image: 'static/images/catalog/necklace/necklace156.png',
    color: '#d4a847',
    gemColor: '#cc2233',
    metalness: 0.95,
    roughness: 0.08,
    price: 'Rs. 450,000',
    rating: 4.9,
    ratingCount: 15,
    material: '22K Gold',
    description: 'Royal heritage set from the catalog collection.',
    tags: ['royal', 'gold', 'set'],
  },
  {
    id: 'n_cat157',
    name: 'Emerald Cascade',
    category: 'necklace',
    type: 'necklace',
    glbFile: 'necklace45.glb',
    image: 'static/images/catalog/necklace/necklace157.png',
    color: '#c0c0c0',
    gemColor: '#2d8a4e',
    metalness: 0.92,
    roughness: 0.08,
    price: 'Rs. 380,000',
    rating: 4.8,
    ratingCount: 22,
    material: 'White Gold + Emerald',
    description: 'Exquisite emerald cascade necklace.',
    tags: ['emerald', 'whitegold', 'cascade'],
  },
  {
    id: 'n_cat158',
    name: 'Ornate Choker',
    category: 'necklace',
    type: 'necklace',
    glbFile: 'necklace12.glb',
    image: 'static/images/catalog/necklace/necklace158.webp',
    color: '#d4a847',
    gemColor: null,
    metalness: 0.94,
    roughness: 0.1,
    price: 'Rs. 290,000',
    rating: 4.7,
    ratingCount: 45,
    material: '22K Gold',
    description: 'Vintage ornate choker design.',
    tags: ['choker', 'vintage', 'gold'],
  },
  {
    id: 'n_cat159',
    name: 'Ruby Tear Drop',
    category: 'necklace',
    type: 'necklace',
    glbFile: 'necklace14.glb',
    image: 'static/images/catalog/necklace/necklace159.png',
    color: '#d4a847',
    gemColor: '#cc2233',
    metalness: 0.95,
    roughness: 0.06,
    price: 'Rs. 410,000',
    rating: 5.0,
    ratingCount: 11,
    material: '22K Gold + Rubies',
    description: 'A beautiful tear drop ruby pendant necklace.',
    tags: ['ruby', 'teardrop', 'gold'],
  },
  {
    id: 'n_cat160',
    name: 'Goddess Mala',
    category: 'necklace',
    type: 'necklace',
    glbFile: 'necklace_b.glb',
    image: 'static/images/catalog/necklace/necklace160.webp',
    color: '#d4a847',
    gemColor: null,
    metalness: 0.9,
    roughness: 0.15,
    price: 'Rs. 510,000',
    rating: 4.9,
    ratingCount: 18,
    material: '22K Antique Gold',
    description: 'Traditional goddess mala with intricate carvings.',
    tags: ['mala', 'antique', 'traditional'],
  },
  {
    id: 'n_cat161',
    name: 'Diamond Swirl',
    category: 'necklace',
    type: 'necklace',
    glbFile: 'necklace78.glb',
    image: 'static/images/catalog/necklace/necklace161.png',
    color: '#c0c0c0',
    gemColor: '#e8f4ff',
    metalness: 0.98,
    roughness: 0.03,
    price: 'Rs. 670,000',
    rating: 5.0,
    ratingCount: 29,
    material: 'Platinum + Diamonds',
    description: 'Modern diamond swirl necklace.',
    tags: ['diamond', 'swirl', 'modern'],
  },
  {
    id: 'n_cat162',
    name: 'Bridal Grandeur',
    category: 'necklace',
    type: 'necklace',
    glbFile: 'necklace15.glb',
    image: 'static/images/catalog/necklace/necklace162.png',
    color: '#d4a847',
    gemColor: '#2d8a4e',
    metalness: 0.95,
    roughness: 0.05,
    price: 'Rs. 890,000',
    rating: 4.9,
    ratingCount: 34,
    material: '22K Gold + Emeralds',
    description: 'Grand Bridal set with elaborate detailing.',
    tags: ['bridal', 'grand', 'gold'],
  },
  {
    id: 'n_cat_360',
    name: 'Sapphire Crescent',
    category: 'necklace',
    type: 'necklace',
    glbFile: 'necklace12.glb',
    image: 'static/images/catalog/necklace/360_F_909676276_X73Br6dCIrVHx19UwNXbrI6JgtP2xfAQ.webp',
    color: '#c0c0c0',
    gemColor: '#1155cc',
    metalness: 0.95,
    roughness: 0.05,
    price: 'Rs. 320,000',
    rating: 4.8,
    ratingCount: 16,
    material: 'White Gold + Sapphires',
    description: 'Crescent necklace featuring deep blue sapphires.',
    tags: ['sapphire', 'crescent', 'whitegold'],
  },
`;

// Find where the RINGS section starts, and insert the necklaces before it.
const replaceTarget = '// ── RINGS ─────────────────────────────────────────────────────';
const insertion = newTryOnNecklaces + newCatalogNecklaces + replaceTarget;

if (code.includes(replaceTarget)) {
    code = code.replace(replaceTarget, insertion);
    fs.writeFileSync('jewelry-data.js', code);
    console.log("Successfully added the new necklaces to the database.");
} else {
    console.log("Failed to find the insertion point.");
}
