// jewelry-data.js — Catalog of all jewelry items (only items with real images)

const JEWELRY_CATALOG = [
  // ── EARRINGS ──────────────────────────────────────────────────
  {
    id: 'e_new1',
    name: 'Royal Heritage Drop',
    category: 'earrings',
    type: 'earring',
    glbFile: 'earring3.glb',
    image: 'static/images/earring/earringrr5.png',
    color: '#d4a847',
    gemColor: '#2d8a4e',
    metalness: 0.95,
    roughness: 0.08,
    price: 'Rs. 140,000',
    rating: 4.9,
    ratingCount: 8,
    material: '22K Gold + Emeralds',
    description: 'Brand new royal heritage drop earrings to complete the perfect jewelry set.',
    tags: ['luxury', 'new', 'gold'],
  },
  {
    id: 'e10',
    name: 'Gold Filigree',
    category: 'earrings',
    type: 'earring',
    glbFile: 'earring.glb',
    image: 'static/images/earring/earring.rr.png',
    color: '#d4a847',
    gemColor: null,
    metalness: 0.9,
    roughness: 0.12,
    price: 'Rs. 88,000',
    rating: 4.6,
    ratingCount: 71,
    material: '22K Gold',
    description: 'Intricate gold filigree earrings showcasing the art of traditional metalwork.',
    tags: ['filigree', 'traditional', 'gold'],
  },
  {
    id: 'e13a',
    name: 'Peacock Drop',
    category: 'earrings',
    type: 'earring',
    glbFile: 'earring3.glb',
    image: 'static/images/earring/earring13.png',
    color: '#d4a847',
    gemColor: '#0055cc',
    metalness: 0.92,
    roughness: 0.08,
    price: 'Rs. 162,000',
    rating: 4.8,
    ratingCount: 29,
    material: '22K Gold + Sapphires',
    description: 'Majestic peacock-inspired drop earrings with sapphires and intricate goldwork.',
    tags: ['peacock', 'sapphire', 'statement'],
  },
  {
    id: 'e13',
    name: 'Peacock Drop Deluxe',
    category: 'earrings',
    type: 'earring',
    glbFile: 'earring3.glb',
    image: 'static/images/earring/earring13 copy.png',
    color: '#d4a847',
    gemColor: '#0055cc',
    metalness: 0.92,
    roughness: 0.08,
    price: 'Rs. 168,000',
    rating: 4.9,
    ratingCount: 33,
    material: '22K Gold + Sapphires',
    description: 'Majestic peacock-inspired drop earrings with sapphires and intricate goldwork.',
    tags: ['peacock', 'sapphire', 'statement'],
  },
  {
    id: 'e14',
    name: 'Vintage Diamond',
    category: 'earrings',
    type: 'earring',
    glbFile: 'earing2.glb',
    image: 'static/images/earring/earring14.png',
    color: '#c0c0c0',
    gemColor: '#e8f4ff',
    metalness: 0.97,
    roughness: 0.04,
    price: 'Rs. 235,000',
    rating: 4.9,
    ratingCount: 21,
    material: 'Platinum + Diamond',
    description: 'Vintage-style diamond earrings in classic platinum setting with exceptional sparkle.',
    tags: ['diamond', 'vintage', 'platinum'],
  },
  {
    id: 'e154',
    name: 'Grand Kundan',
    category: 'earrings',
    type: 'earring',
    glbFile: 'earring3.glb',
    image: 'static/images/earring/earring154 copy.png',
    color: '#d4a847',
    gemColor: '#cc2233',
    metalness: 0.93,
    roughness: 0.09,
    price: 'Rs. 185,000',
    rating: 4.8,
    ratingCount: 17,
    material: '22K Gold + Kundhan',
    description: 'Grand kundan earrings with polished stone setting in traditional Rajasthani style.',
    tags: ['kundan', 'grand', 'traditional'],
  },
  {
    id: 'e_rr2',
    name: 'Emerald Cascade',
    category: 'earrings',
    type: 'earring',
    glbFile: 'earing4.glb',
    image: 'static/images/earring/earringrr2.png',
    color: '#d4a847',
    gemColor: '#2d8a4e',
    metalness: 0.94,
    roughness: 0.08,
    price: 'Rs. 210,000',
    rating: 4.9,
    ratingCount: 14,
    material: '22K Gold + Emeralds',
    description: 'Cascading emerald drop earrings with an intricate waterfall design in pure gold.',
    tags: ['cascade', 'emerald', 'luxe'],
  },
  {
    id: 'e_rr3',
    name: 'Heritage Drops',
    category: 'earrings',
    type: 'earring',
    glbFile: 'earring3.glb',
    image: 'static/images/earring/earringrr3.png',
    color: '#d4a847',
    gemColor: '#cc2233',
    metalness: 0.92,
    roughness: 0.1,
    price: 'Rs. 175,000',
    rating: 4.8,
    ratingCount: 19,
    material: '22K Gold + Rubies',
    description: 'Heritage-style drop earrings featuring deep ruby settings in ornate gold frames.',
    tags: ['heritage', 'ruby', 'traditional'],
  },
  {
    id: 'e_rr4',
    name: 'Bridal Lumba Set',
    category: 'earrings',
    type: 'earring',
    glbFile: 'earing2.glb',
    image: 'static/images/earring/earringrr4.png',
    color: '#d4a847',
    gemColor: '#2d8a4e',
    metalness: 0.95,
    roughness: 0.07,
    price: 'Rs. 245,000',
    rating: 5.0,
    ratingCount: 11,
    material: '22K Gold + Emeralds',
    description: 'Stunning bridal lumba earring set with emerald accents perfect for wedding occasions.',
    tags: ['bridal', 'lumba', 'emerald'],
  },
  {
    id: 'e_cat2',
    name: 'Elegant Jhumka',
    category: 'earrings',
    type: 'earring',
    glbFile: 'earring3.glb',
    image: 'static/images/catalog/earring/earring-2.avif',
    color: '#d4a847',
    gemColor: '#cc2233',
    metalness: 0.92,
    roughness: 0.1,
    price: 'Rs. 95,000',
    rating: 4.7,
    ratingCount: 42,
    material: '22K Gold',
    description: 'Traditional jhumka earrings with intricate goldwork and delicate bell drops.',
    tags: ['jhumka', 'traditional', 'gold'],
  },
  {
    id: 'e_cat3',
    name: 'Designer Chandbali',
    category: 'earrings',
    type: 'earring',
    glbFile: 'earing4.glb',
    image: 'static/images/catalog/earring/earring-3.avif',
    color: '#d4a847',
    gemColor: '#2d8a4e',
    metalness: 0.95,
    roughness: 0.08,
    price: 'Rs. 125,000',
    rating: 4.9,
    ratingCount: 31,
    material: '22K Gold + Emeralds',
    description: 'Exquisite chandbali earrings featuring emerald stones and intricate filigree work.',
    tags: ['chandbali', 'designer', 'emerald'],
  },

  // ── NECKLACES ─────────────────────────────────────────────────
  {
    id: 'n_new1',
    name: 'Royal Heritage Necklace',
    category: 'necklace',
    type: 'necklace',
    glbFile: 'necklace15.glb',
    image: 'static/images/necklace/necklacerr5.png',
    color: '#d4a847',
    gemColor: '#2d8a4e',
    metalness: 0.95,
    roughness: 0.08,
    price: 'Rs. 320,000',
    rating: 5.0,
    ratingCount: 12,
    material: '22K Gold + Emeralds',
    description: 'The newest stunning royal design uploaded to the catalogue.',
    tags: ['luxury', 'new', 'gold'],
  },
  {
    id: 'n3',
    name: 'Emerald Collar',
    category: 'necklace',
    type: 'necklace',
    glbFile: 'necklace15.glb',
    image: 'static/images/necklace/necklacerr3.png',
    color: '#c0c0c0',
    gemColor: '#2d8a4e',
    metalness: 0.92,
    roughness: 0.08,
    price: 'Rs. 276,150',
    rating: 4.8,
    ratingCount: 143,
    material: 'White Gold + Emerald',
    description: 'A stunning collar necklace featuring vivid Colombian emeralds set in white gold.',
    tags: ['emerald', 'collar', 'luxury'],
  },
  {
    id: 'n4',
    name: 'Golden Chain',
    category: 'necklace',
    type: 'necklace',
    glbFile: 'necklace45.glb',
    image: 'static/images/necklace/necklace150.png',
    color: '#d4a847',
    gemColor: null,
    metalness: 0.95,
    roughness: 0.05,
    price: 'Rs. 104,650',
    rating: 4.6,
    ratingCount: 211,
    material: '22K Gold',
    description: 'A classic solid 22K gold link chain with a lustrous finish.',
    tags: ['chain', 'gold', 'classic'],
  },
  {
    id: 'n5',
    name: 'Diamond Choker',
    category: 'necklace',
    type: 'necklace',
    glbFile: 'necklace78.glb',
    image: 'static/images/necklace/necklace155.png',
    color: '#c0c0c0',
    gemColor: '#e8f4ff',
    metalness: 0.98,
    roughness: 0.03,
    price: 'Rs. 419,650',
    rating: 5.0,
    ratingCount: 312,
    material: 'Platinum + Diamonds',
    description: 'An exquisite platinum choker set with brilliant-cut diamonds all around.',
    tags: ['diamond', 'choker', 'luxury'],
  },
  {
    id: 'n7',
    name: 'Bead Necklace',
    category: 'necklace',
    type: 'necklace',
    glbFile: 'necklace_b.glb',
    image: 'static/images/necklace/necklacerr2.png',
    color: '#8b7355',
    gemColor: '#aa4422',
    metalness: 0.5,
    roughness: 0.4,
    price: 'Rs. 62,650',
    rating: 4.4,
    ratingCount: 95,
    material: 'Gold + Coral',
    description: 'Hand-strung coral and gold bead necklace with artisan craftsmanship.',
    tags: ['beads', 'coral', 'artisan'],
  },
  {
    id: 'n8',
    name: 'Custom Necklace 66',
    category: 'necklace',
    type: 'necklace',
    glbFile: 'necklace12.glb',
    image: 'static/images/necklace/necklace66.png',
    color: '#d4a847',
    gemColor: null,
    metalness: 0.95,
    roughness: 0.08,
    price: 'Rs. 150,000',
    rating: 4.9,
    ratingCount: 14,
    material: '18K Gold',
    description: 'A delicate and exquisite piece from our custom catalog collection.',
    tags: ['custom', 'elegant', 'gold'],
  },
  {
    id: 'n9',
    name: 'Long Elegance',
    category: 'necklace',
    type: 'necklace',
    glbFile: 'necklace15.glb',
    image: 'static/images/necklace/necklace69 copy.png',
    color: '#d4a847',
    gemColor: null,
    metalness: 0.95,
    roughness: 0.08,
    price: 'Rs. 220,000',
    rating: 4.8,
    ratingCount: 11,
    material: '22K Gold',
    description: 'An elegant long necklace combining traditional flair with modern sensibilities.',
    tags: ['custom', 'traditional', 'gold'],
  },
  {
    id: 'n_custom_5',
    name: 'Floral Drop Necklace',
    category: 'necklace',
    type: 'necklace',
    glbFile: 'necklace45.glb',
    image: 'static/images/necklace/custom_n5.png',
    color: '#d4a847',
    gemColor: '#cc2233',
    metalness: 0.95,
    roughness: 0.08,
    price: 'Rs. 280,000',
    rating: 4.8,
    ratingCount: 28,
    material: '22K Antique Gold',
    description: 'Elegant drop necklace featuring repeating floral motifs ending in a teardrop ruby.',
    tags: ['floral', 'gold', 'antique'],
  },
  {
    id: 'n_cat1',
    name: 'Classic Temple Necklace',
    category: 'necklace',
    type: 'necklace',
    glbFile: 'necklace14.glb',
    image: 'static/images/catalog/necklace/necklace-1.avif',
    color: '#d4a847',
    gemColor: '#cc2233',
    metalness: 0.95,
    roughness: 0.08,
    price: 'Rs. 285,000',
    rating: 4.8,
    ratingCount: 19,
    material: '22K Gold + Rubies',
    description: 'Classic temple-style necklace with ruby accents and traditional motifs.',
    tags: ['temple', 'classic', 'gold'],
  },
  {
    id: 'n_cat2',
    name: 'Mango Mala Necklace',
    category: 'necklace',
    type: 'necklace',
    glbFile: 'necklace12.glb',
    image: 'static/images/catalog/necklace/necklace-2.avif',
    color: '#d4a847',
    gemColor: null,
    metalness: 0.93,
    roughness: 0.1,
    price: 'Rs. 345,000',
    rating: 4.9,
    ratingCount: 25,
    material: '22K Gold',
    description: 'Traditional mango mala necklace with signature paisley-shaped gold beads.',
    tags: ['mango', 'mala', 'traditional'],
  },
  {
    id: 'n_cat3',
    name: 'Grand Bridal Set',
    category: 'necklace',
    type: 'necklace',
    glbFile: 'necklace15.glb',
    image: 'static/images/catalog/necklace/necklace=3.avif',
    color: '#d4a847',
    gemColor: '#2d8a4e',
    metalness: 0.95,
    roughness: 0.06,
    price: 'Rs. 520,000',
    rating: 5.0,
    ratingCount: 38,
    material: '22K Gold + Emeralds',
    description: 'A grand bridal necklace set featuring emeralds and intricate goldwork.',
    tags: ['bridal', 'grand', 'emerald'],
  },
  {
    id: 'n_cat4',
    name: 'Rani Haar Long Necklace',
    category: 'necklace',
    type: 'necklace',
    glbFile: 'necklace45.glb',
    image: 'static/images/catalog/necklace/necklace=4.avif',
    color: '#d4a847',
    gemColor: '#cc2233',
    metalness: 0.94,
    roughness: 0.08,
    price: 'Rs. 460,000',
    rating: 4.8,
    ratingCount: 16,
    material: '22K Gold + Rubies',
    description: 'Majestic rani haar long necklace with ruby stones and elaborate gold chain design.',
    tags: ['rani-haar', 'long', 'rubies'],
  },

  // ── RINGS ─────────────────────────────────────────────────────
  {
    id: 'r1',
    name: 'Solitaire Diamond',
    category: 'rings',
    type: 'ring',
    glbFile: 'ring1-v1.glb',
    image: 'static/images/catalog/ring/ring1.avif',
    color: '#d4a847',
    gemColor: '#f0f8ff',
    metalness: 0.95,
    roughness: 0.04,
    price: 'Rs. 454,650',
    rating: 5.0,
    ratingCount: 874,
    material: '18K Gold + Diamond',
    description: 'The quintessential diamond solitaire ring. A 1.5-carat round brilliant diamond in a six-prong 18K gold setting.',
    tags: ['diamond', 'solitaire', 'engagement'],
  },
  {
    id: 'r2',
    name: 'Amethyst Cocktail',
    category: 'rings',
    type: 'ring',
    glbFile: 'ring (2).glb',
    image: 'static/images/catalog/ring/ring2.avif',
    color: '#c0a0d0',
    gemColor: '#8b3ec1',
    metalness: 0.8,
    roughness: 0.2,
    price: 'Rs. 97,650',
    rating: 4.6,
    ratingCount: 231,
    material: 'Rose Gold + Amethyst',
    description: 'A bold cocktail ring featuring a large oval amethyst set in rose gold.',
    tags: ['amethyst', 'cocktail', 'statement'],
  },
  {
    id: 'r3',
    name: 'Eternity Band',
    category: 'rings',
    type: 'ring',
    glbFile: 'ring (3).glb',
    image: 'static/images/catalog/ring/ring3.avif',
    color: '#e8e8e8',
    gemColor: '#e8f4ff',
    metalness: 0.98,
    roughness: 0.02,
    price: 'Rs. 244,650',
    rating: 4.9,
    ratingCount: 556,
    material: 'Platinum + Diamonds',
    description: 'A full platinum eternity band paved with brilliant-cut diamonds.',
    tags: ['diamond', 'eternity', 'band'],
  },
  {
    id: 'r4',
    name: 'Twisted Gold',
    category: 'rings',
    type: 'ring',
    glbFile: 'ring(56).glb',
    image: 'static/images/catalog/ring/ring4.avif',
    color: '#d4a847',
    gemColor: null,
    metalness: 0.9,
    roughness: 0.12,
    price: 'Rs. 122,150',
    rating: 4.7,
    ratingCount: 203,
    material: '18K Gold',
    description: 'A boldly twisted 18K gold band with a modern sculptural aesthetic.',
    tags: ['twist', 'gold', 'modern'],
  },
  {
    id: 'r5',
    name: 'Ruby Signet',
    category: 'rings',
    type: 'ring',
    glbFile: 'ring(6).glb',
    image: 'static/images/catalog/ring/ring5.avif',
    color: '#8b7355',
    gemColor: '#cc2233',
    metalness: 0.85,
    roughness: 0.18,
    price: 'Rs. 174,650',
    rating: 4.8,
    ratingCount: 164,
    material: '14K Gold + Ruby',
    description: 'A bold signet ring featuring a deep red ruby cabochon set in yellow gold.',
    tags: ['ruby', 'signet', 'bold'],
  },
  {
    id: 'r6',
    name: 'Sapphire Cluster',
    category: 'rings',
    type: 'ring',
    glbFile: 'ring(65).glb',
    image: 'static/images/catalog/ring/ring6.avif',
    color: '#c0c0c0',
    gemColor: '#1155cc',
    metalness: 0.93,
    roughness: 0.07,
    price: 'Rs. 297,150',
    rating: 4.8,
    ratingCount: 287,
    material: 'White Gold + Sapphires',
    description: 'A breathtaking cluster ring with Ceylon sapphires surrounding a central stone.',
    tags: ['sapphire', 'cluster', 'luxury'],
  },
];

// Helper: get items by category
function getByCategory(cat) {
  return JEWELRY_CATALOG.filter(j => j.category === cat);
}
